# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1930e771e94256b160fe502cd3612522f96f7ec9a2a4129387ebd78ab3ac7e79ef321246458c42db80d4b361d9717ba12736e564a2cacfc6d79f792517e66f16

test:
  secret_key_base: 53132901470ada40d405a890e80e06a8645e826e3dc709470f39041a90828accb2451d952b52df7bf4e4599926ebc981724ee1480deca2fce8550a21bb43260f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
